config/routes.rb
Rails.application.routes.draw do
  resources :productos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "/", to:"productos#index"

  #Si cambio un link_to por un button_to, debo crear un post
  post "/productos/new", to:"productos#new"

  #Para el boton editar en la vista show, debo crear un get y un post
  get "/productos/:id/edit(.:format)",to:"productos#edit"
  post "/productos/:id/edit(.:format)", to:"productos#edit"
 
 
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/producto.rb
class Producto < ApplicationRecord
    has_one_attached:image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
    @textboton = "Crear"
  end

  # GET /productos/1/edit
  def edit
    @textboton = "Guardar"
  end

  # POST /productos or /productos.json
  def create

    @busqueda = Producto.find_by(codigo: producto_params[:codigo])

    if @busqueda.present?

      respond_to do |format|
        format.html { redirect_to "/productos/new", notice: "Código duplicado." }
        format.json { render :new, status: :ok, location: @producto }
      end

    else
      @producto = Producto.new(producto_params)

      if @producto.save 
        respond_to do |format|
          format.html { redirect_to producto_url(@producto), notice: "El producto ha sido creado." }
          format.json { render :show, status: :ok, location: @producto }
        end
      end
    end

  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update

    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "El producto ha sido actualizado." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "El producto ha sido eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:image,:codigo, :nombre, :descripcion, :precio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libreria de Daniela</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "miestilo", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style_pcgram", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <!-- Bootstrap .container class is a responsive, fixed-width container, meaning its max-width changes at each breakpoint. -->
    <!--header-->
      <!--cinta superior-->
        <div class="container">
          <div class="row d-flex align-items-center">
              <div class="col-7 d-flex align-items-center justify-content-between">
                Envios a todo Chile
              </div>
              <div class="col-5 d-flex align-items-center justify-content-between">
                <a href="">
                  <img src="http://drive.google.com/uc?export=view&id=1OlUZZl4rECPNrCrQtZ0y3qlSSU48wXMh" alt="" width="30" height="30" class="float-right img-fluid d-inline-block align-text-top">
                </a>
                <span>Llamanos</span>
                <a href="">
                  <img src="http://drive.google.com/uc?export=view&id=1Py61Nf3mBA6UvfsJJiI0-2KpfZMai1nm" alt="" width="30" height="30" class="float-right img-fluid d-inline-block align-text-top">	
                </a>
                <span>Ayuda</span>
                <a href="">
                  <img src="http://drive.google.com/uc?export=view&id=1nDhV7HZPzjHKP28iatKJFjzpp4t2gcpM" alt="" width="30" height="30" class="float-right img-fluid d-inline-block align-text-top">
                </a>
                <span>Registrate</span>
                <a href="">
                  <img src="http://drive.google.com/uc?export=view&id=1Oadmir4dZABdqf38isEsJ0QeB4ba792v" alt="" width="30" height="30" class="float-right img-fluid d-inline-block align-text-top">	
                </a>
              <span>Inicio</span>        
              </div>
            </div>
        </div>
      <br>

      <!--barra busqueda-->
        <div class="container">
          <div class="row d-flex align-items-center">
            <div class="col-2">
              <img src="http://drive.google.com/uc?export=view&id=1LEqxkUgnlSUl-u0HivuziaLkZSy9tJoy" alt=""  height="48" class="img-fluid">
            </div>
            <div class="col-4">
              <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Escribe aqui" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
            <div class="col-2">
              <img src="http://drive.google.com/uc?export=view&id=1Py5QJMXqiTq6eWKrzWkFjZ-iicl6K62Q" alt="" height="30" class="">
              <img src="http://drive.google.com/uc?export=view&id=1OcwKQUcQdfX4XWK0P5dXd1C9JPNSA3KF" alt="" height="30" class="">
            </div>
            <div class="col-4 d-flex align-items-center justify-content-between">
              <img src="http://drive.google.com/uc?export=view&id=1Or7qRndX_InywFXgG-Y4xCF7fjMyW9IK" alt="" height="30" class="">
              <span class="text-left">seguimiento</span>
              <span>  </span>
              <img src="http://drive.google.com/uc?export=view&id=1OZWXF2Ui2C5GeCBXBAlwazWkbi23IR1_" alt="" height="30" class="">
              <span class="text-left">comparar</span>
              <span>  </span>
              <img src="http://drive.google.com/uc?export=view&id=1OvZ_vCJM74tlcu4ZyB2WaDDvCLLRy8Ar" alt="" height="30" class="">
              <span class="text-left">busqueda</span>
            </div>
          </div>
        </div>
      <br>
      <!--barra navegacion-->
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="#">Portatiles</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Computadores</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Partes y piezas</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Almacenamiento</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Apple</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="#">Monitores</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="#">Proyectores</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="#">Impresoras</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="#">Tintas/Toner</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="#">Servidores</a>
                  </li> <li class="nav-item">
                    <a class="nav-link" href="#">Redes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Accesorios</a>
                  </li> 
                  <li class="nav-item">
                    <a class="nav-link" href="#">+ categorias</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>
    <!--yield-->
    <div class="container productos">
      <%= yield %>
    </div>
    <br>
    <!--footer-->
      <!--botones-->
        <div class="container">
          <div class="row">
            <div class="col-3">
              <a href="">
                  <img  height="55" src="http://drive.google.com/uc?export=view&id=1Or7qRndX_InywFXgG-Y4xCF7fjMyW9IK" >
              </a>
              <span>ESTADO DE COMPRA</span>
            </div>
            <div class="col-3">
              <a href="">
                  <img height="55" src="http://drive.google.com/uc?export=view&id=1O_Wm35t4-yAFpwhJKuwTQwvFdTpR5GUO" >
              </a>
              <span>CONTACTANOS</span>

            </div>
            <div class="col-3">
              <a href="">
                  <img height="55" src="http://drive.google.com/uc?export=view&id=1OlUZZl4rECPNrCrQtZ0y3qlSSU48wXMh" >
              </a>
              <span>+569 12345678</span>

            </div>
            <div class="col-3">
              <a href="">
                  <img height="55" src="http://drive.google.com/uc?export=view&id=1Py61Nf3mBA6UvfsJJiI0-2KpfZMai1nm" >         
              </a>
              <span>CENTRO DE AYUDA</span>
            </div>
          </div>
        </div>
      <br>
      <!--listas-->
        <div class="container">
          <div class="row">
            <!--primera columna, logos-->
              <div class="col-3">
                <div class="row d-flex align-items-center">
                  <a href="">
                     <img src="http://drive.google.com/uc?export=view&id=1LEqxkUgnlSUl-u0HivuziaLkZSy9tJoy" height="80" alt="Responsive image">
                  </a>
                </div>
                <div class="row d-flex align-items-center">
                  <div class="col">
                    <a href="">
                      <img src="http://drive.google.com/uc?export=view&id=1TcRwNF17GlOhTmzxOiaGCk1MMHvyIgL0" height="20" alt="Responsive image">
                    </a>
                    <span></span>
                  </div>
                  <div class="col">
                    <a href="">
                      <img src="http://drive.google.com/uc?export=view&id=1Tdh1Q31ZTMlTHU_ND6wtVAVdFX5eekAJ" height="20" alt="Responsive image">
                    </a>
                    <span></span>
                  </div>
                  <div class="col">
                    <a href="">
                      <img src="http://drive.google.com/uc?export=view&id=1TT_gxjHFEkFAtp8rgT91SB9KeregEfQJ" height="20" alt="Responsive image" >
                    </a>
                    <span></span>
                  </div>
                </div>
              </div>
            <!--segunda columna, acerca de-->
              <div class="col-3">
                <nav>
                  <ul>
                    <li><a class="enlaces" href="/que-es-winpy" title="Acerca de Nosotros">Acerca de Nosotros</a></li>
                    <li><a class="enlaces" href="/politicas-de-privacidad" title="Póliticas de Privacidad">Póliticas de Privacidad</a></li>
                    <li><a class="enlaces" href="https://winpy.zendesk.com/hc/es/sections/115001408088-Garant%C3%ADas-" target="_blank" title="Garantías">Garantías</a></li>
                    <li><a class="enlaces" href="/trabaja-con-nosotros/" title="Trabaja Con Nosotros">Trabaja Con Nosotros</a></li>
                  </ul>
                </nav>
              </div>
            <!--tercera columna, politicas-->
              <div class="col-3">
                <nav>
                  <ul>
                    <li><a class="enlaces" href="/estado-de-compra/" title="Revisa el estado de tu Compra">Estado de tu compra</a></li>
                    <li><a class="enlaces" href="https://winpy.zendesk.com/hc/es/sections/115001408108-Retiros-y-Despachos" target="_blank" title="Retiros y Despachos">Retiros y Despachos</a></li>
                    <li><a class="enlaces" href="https://winpy.zendesk.com/hc/es/sections/115001402087-Formas-de-Pago" target="_blank" title="Formas de Pago">Formas de Pago</a></li>
                    <li><a class="enlaces" href="/solicita-factura/" title="Facturación Electrónica">Facturación Electrónica</a></li>
                  </ul>
                </nav>
              </div>
            <!--cuarta columna, seguridad-->
              <div class="col-3">
                <p>Todas tus compras estan seguras</p>
                <img src="http://drive.google.com/uc?export=view&id=1RHyckzLywizGEPosDfqfJ1CNAZIVXfWk" alt="Certificado SSL" class="img-fluid">
                <img src="http://drive.google.com/uc?export=view&id=1RX_zMlosclVEX3DNZctRCLx16EQZ6t1J" alt="Webpay Plus" class="img-fluid">
              </div>
          </div>
          <div class="row">
          </div>
        </div>
      <br>
      <!--cinta inferior-->
        <div class="container">
          <div class="row text-center" style="background: #f3f3f3">
            <span>PC GRAM | TODOS LOS DERECHOS RESERVADOS</span>
          </div>
        </div>

  <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :codigo, style: "display: block" %>
    <%= form.number_field :codigo, min:1 %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.number_field :precio, min:0 %>
  </div>

  <p>
    <p>Imagen subida:</p>
    <% if producto.image.attached? %>
      <%= image_tag producto.image, :class => "img-fluid"%>
    <% end %>
  </p> 

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
<br>

  <div>
    <%= form.submit @textboton %>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">

  <p>
    <strong>Codigo:</strong>
    <%= producto.codigo %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= producto.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= producto.descripcion %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= producto.precio %>
  </p>

  <p>
    <strong>Imagen subida:</strong>
    <% if producto.image.attached? %>
      <%= image_tag producto.image, :class => "img-fluid"%>
    <% end %>
  </p>  

</div>

app/views/productos/edit.html.erb
<h1>Editar producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Ver", @producto %> |
  <%= link_to "Volver", productos_path %>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Productos</h1>

<div id="productos">

  <!--intento 1 de meter los productos en una tabla-->
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Código</th>
        <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Precio</th>
        <th scope="col">Imagen</th>
        <th scope="col">Acción</th>
      </tr>
    </thead>
    <tbody>
      <% @productos.each do |producto| %>
        <tr class="align-middle">
          <th scope="row">
            <% if producto.image.attached? %>
              <%= image_tag producto.image, :class => "img-fluid"%>
            <% end %>
          </th>
          <td><%=producto.codigo%></td>
          <td><%=producto.nombre%></td>
          <td><%=producto.descripcion%></td>
          <td><%=producto.precio%></td>

          <td><%= link_to "Ver", producto %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<%= button_to "Crear nuevo producto",  new_producto_path %>

app/views/productos/new.html.erb
<p style="color: green"><%= notice %></p>

<h1>Crear</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Volver", productos_path %>
</div>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div>
  <%= button_to "Editar", edit_producto_path(@producto) %>
  <%= button_to "Eliminar", @producto, method: :delete %> 
  <%= link_to "Volver", productos_path %>
</div>